import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync, copyFileSync, chmodSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";

// Pinned, not "latest" - this exact version's GLIBC requirement (2.29) and
// end-to-end behavior (Lambda Web Adapter + provided.al2023, cold-start Init
// Duration ~380-436ms) were verified directly against a real Lambda before
// this build step existed. Bump deliberately, re-verify, don't auto-track.
const ROUTER_VERSION = "1.61.1";
const ARTIFACT = `router-v${ROUTER_VERSION}-x86_64-unknown-linux-gnu.tar.gz`;
const RELEASE_BASE = `https://github.com/apollographql/router/releases/download/v${ROUTER_VERSION}`;

// Same subgraph names as compose-supergraph.ts's SERVICES - duplicated
// rather than imported since that file's entries also carry typeDefs this
// script has no use for. Keep in sync by hand, same tolerance this codebase
// already has for WARM_SCHEDULE_PROJECTS in infra/lib/warm-schedule-stack.ts.
const SUBGRAPH_NAMES = ["portfolio", "pantry", "imposter", "design-studio"];

const root = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(root, "..");
const distDir = join(packageRoot, "dist");

async function download(url: string): Promise<Buffer> {
  const res = await fetch(url);
  if (!res.ok)
    throw new Error(`[build-router-package] failed to download ${url}: ${res.status} ${res.statusText}`);

  return Buffer.from(await res.arrayBuffer());
}

// Pulled out as a pure function so the supply-chain-integrity check itself
// (not just the network calls around it) has a real unit test - throws
// rather than returning a boolean so a mismatch can't be silently ignored
// by a caller that forgets to check a return value.
export function verifyChecksum(artifactBuf: Buffer, sumsText: string, artifactName: string): string {
  const sumsLine = sumsText.split("\n").find((line) => line.trim().endsWith(artifactName));
  if (!sumsLine) throw new Error(`[build-router-package] no sha256sums.txt entry found for ${artifactName}`);

  const expectedHash = sumsLine.trim().split(/\s+/)[0];
  const actualHash = createHash("sha256").update(artifactBuf).digest("hex");
  if (actualHash !== expectedHash) {
    throw new Error(
      `[build-router-package] sha256 mismatch for ${artifactName}: expected ${expectedHash}, got ${actualHash}`
    );
  }

  return actualHash;
}

// Pulled out as a pure function so router.yaml's shape - especially the
// authorization header propagation (see the comment at its call site below)
// and the /graphql path (see infra/lib/api-gateway-stack.ts's routes array)
// - has a real unit test instead of only being covered by eyeballing a
// build's output.
export function buildRouterYaml(subgraphNames: string[]): string {
  const overrideLines = subgraphNames.map((name) => `  ${name}: \${env.API_BASE_URL}/${name}`).join("\n");

  return (
    "# AUTO-GENERATED by scripts/build-router-package.ts - do not edit by hand.\n" +
    "override_subgraph_url:\n" +
    `${overrideLines}\n` +
    "\n" +
    // pantry is the only subgraph that reads this today (see
    // cognito-auth.ts) - without it, RemoteGraphQLDataSource's old Node
    // equivalent already didn't forward client headers on its own, and
    // Router doesn't either, so a signed-in pantry request would silently
    // fall back to anonymous/shared-pantry behavior. Verified directly: a
    // local echo subgraph confirmed this config actually forwards a real
    // `authorization: Bearer ...` header through.
    "headers:\n" +
    "  all:\n" +
    "    request:\n" +
    '      - propagate:\n          named: "authorization"\n' +
    "\n" +
    // infra/lib/api-gateway-stack.ts's defaultCorsPreflightOptions only
    // answers the browser's OPTIONS preflight via a mock integration that
    // never reaches this Lambda - it does NOT add CORS headers to the
    // actual GET/POST response coming back through the proxy integration.
    // The old Node handler added them itself via api-shared/http.ts's
    // corsHeaders() on every response; Router needs the equivalent here or
    // browsers silently discard every real response (the request itself
    // still succeeds - curl won't show anything wrong, only a real browser
    // enforcing CORS will). Keep this origin list in sync with both
    // corsHeaders()'s ALLOWED_ORIGINS and api-gateway-stack.ts's
    // allowOrigins.
    "cors:\n" +
    "  origins:\n" +
    "    - https://www.petertran.au\n" +
    "    - https://petertran.au\n" +
    "    - https://test.petertran.au\n" +
    "    - https://www.test.petertran.au\n" +
    "    - http://localhost:5173\n" +
    "    - http://localhost:3000\n" +
    "\n" +
    "supergraph:\n" +
    "  listen: 127.0.0.1:8080\n" +
    // ApiGatewayStack routes the exact path /graphql to this Lambda (see
    // infra/lib/api-gateway-stack.ts's routes array) - Router's own
    // default is "/", which 404s under that routing. introspection:true
    // matches the old Node handler's `new ApolloServer({ introspection:
    // true })`, which the dashboard's GraphiQL/schema tooling relies on.
    "  path: /graphql\n" +
    "  introspection: true\n"
  );
}

async function main() {
  rmSync(distDir, { recursive: true, force: true });
  mkdirSync(distDir, { recursive: true });

  console.log(`[build-router-package] downloading Router v${ROUTER_VERSION}...`);

  const [artifactBuf, sumsBuf] = await Promise.all([
    download(`${RELEASE_BASE}/${ARTIFACT}`),
    download(`${RELEASE_BASE}/sha256sums.txt`),
  ]);

  const actualHash = verifyChecksum(artifactBuf, sumsBuf.toString("utf-8"), ARTIFACT);
  console.log(`[build-router-package] sha256 verified: ${actualHash}`);

  const tmpDir = mkdtempSync(join(tmpdir(), "router-download-"));
  const tarPath = join(tmpDir, ARTIFACT);
  writeFileSync(tarPath, artifactBuf);
  execFileSync("tar", ["-xzf", tarPath, "-C", tmpDir]);

  const extractedBinary = join(tmpDir, "dist", "router");
  const routerOutPath = join(distDir, "router");
  copyFileSync(extractedBinary, routerOutPath);
  chmodSync(routerOutPath, 0o755);
  rmSync(tmpDir, { recursive: true, force: true });
  console.log(`[build-router-package] wrote ${routerOutPath}`);

  const bootstrapPath = join(distDir, "bootstrap");
  writeFileSync(
    bootstrapPath,
    "#!/bin/sh\n" +
      "exec /var/task/router --supergraph /var/task/supergraph.graphql --config /var/task/router.yaml --log info\n"
  );
  chmodSync(bootstrapPath, 0o755);
  console.log(`[build-router-package] wrote ${bootstrapPath}`);

  const routerYamlPath = join(distDir, "router.yaml");
  writeFileSync(routerYamlPath, buildRouterYaml(SUBGRAPH_NAMES));
  console.log(`[build-router-package] wrote ${routerYamlPath}`);

  const sdlSourcePath = join(packageRoot, "supergraph.generated.graphql");
  const sdlOutPath = join(distDir, "supergraph.graphql");
  copyFileSync(sdlSourcePath, sdlOutPath);
  console.log(`[build-router-package] wrote ${sdlOutPath}`);
}

// Guarded so a test can import verifyChecksum/buildRouterYaml above without
// also triggering a real network download as a side effect of the import.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
