import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, it, expect } from "vitest";
import { verifyChecksum } from "./build-router-package";

const routerYamlPath = join(dirname(fileURLToPath(import.meta.url)), "..", "router.yaml");
const routerYaml = readFileSync(routerYamlPath, "utf-8");

describe("verifyChecksum", () => {
  it("returns the hash when it matches the sha256sums.txt entry", () => {
    const artifactBuf = Buffer.from("fake router binary contents");
    const artifactName = "router-v2.16.0-x86_64-unknown-linux-gnu.tar.gz";
    const hash = createHash("sha256").update(artifactBuf).digest("hex");
    const sumsText = `${hash}  ${artifactName}\nsomeotherhash  some-other-file.tar.gz\n`;

    expect(verifyChecksum(artifactBuf, sumsText, artifactName)).toBe(hash);
  });

  it("throws on a hash mismatch instead of silently continuing", () => {
    const artifactBuf = Buffer.from("fake router binary contents");
    const artifactName = "router-v2.16.0-x86_64-unknown-linux-gnu.tar.gz";
    const sumsText = `0000000000000000000000000000000000000000000000000000000000000000  ${artifactName}\n`;

    expect(() => verifyChecksum(artifactBuf, sumsText, artifactName)).toThrow("sha256 mismatch");
  });

  it("throws when sha256sums.txt has no entry for the artifact", () => {
    const artifactBuf = Buffer.from("fake router binary contents");
    const artifactName = "router-v2.16.0-x86_64-unknown-linux-gnu.tar.gz";
    const sumsText = "somehash  some-unrelated-file.tar.gz\n";

    expect(() => verifyChecksum(artifactBuf, sumsText, artifactName)).toThrow(
      "no sha256sums.txt entry found"
    );
  });
});

// router.yaml is a static, checked-in file now (not generated by this
// script) - these tests read it directly, so they're regression tests
// against hand-edits rather than against a build step's own logic.
describe("router.yaml", () => {
  it("routes each subgraph name to API_BASE_URL via Router's own env templating", () => {
    expect(routerYaml).toContain("portfolio: ${env.API_BASE_URL}/portfolio");
    expect(routerYaml).toContain("pantry: ${env.API_BASE_URL}/pantry");
    expect(routerYaml).toContain("imposter: ${env.API_BASE_URL}/imposter");
    expect(routerYaml).toContain("design-studio: ${env.API_BASE_URL}/design-studio");
  });

  it("propagates the authorization header to subgraphs", () => {
    // Regression test: Router 2.x requires an `operations:` key wrapping
    // the propagation-rule list - Router 1.x accepted the list directly
    // under `request:`. Confirmed via the real pinned binary's own
    // `router config upgrade` against this exact file.
    expect(routerYaml).toMatch(/request:\s*\n\s*operations:\s*\n\s*- propagate:/);
    expect(routerYaml).toContain('named: "authorization"');
  });

  it("allows CORS from prod, test-env, local dev, and the embedded Sandbox UI on the actual response", () => {
    // Regression test: API Gateway's mock integration only answers the
    // OPTIONS preflight - it does not add CORS headers to the actual
    // GET/POST response, so without this config every browser (not curl)
    // silently discards every real response.
    //
    // Origins live under cors.policies[0].origins, not a flat cors.origins
    // list, as of the Router 2.x config migration - confirmed via the real
    // pinned binary's own `router config upgrade` against this exact file.
    expect(routerYaml).toContain("cors:");
    expect(routerYaml).toMatch(/cors:\s*\n\s*allow_credentials: true\s*\n\s*policies:\s*\n\s*- origins:/);
    expect(routerYaml).toContain("https://www.petertran.au");
    expect(routerYaml).toContain("https://petertran.au");
    expect(routerYaml).toContain("https://test.petertran.au");
    expect(routerYaml).toContain("https://www.test.petertran.au");
    expect(routerYaml).toContain("http://localhost:5173");
    expect(routerYaml).toContain("http://localhost:3000");
    expect(routerYaml).toContain("https://studio.apollographql.com");
  });

  it("serves GraphQL at /graphql to match ApiGatewayStack's routing", () => {
    expect(routerYaml).toContain("path: /graphql");
  });

  it("enables sandbox and disables homepage together, never one without the other", () => {
    // Regression test: Router refuses to start at all if both are true
    // (homepage defaults to true) - crashed every cold start in production
    // once already ("sandbox and homepage cannot be enabled at the same
    // time"), only caught after real traffic was affected.
    expect(routerYaml).toMatch(/sandbox:\s*\n\s*enabled: true/);
    expect(routerYaml).toMatch(/homepage:\s*\n\s*enabled: false/);
  });

  it("propagates X-Ray trace headers to subgraphs without an OTLP exporter/ADOT layer", () => {
    // No ADOT collector layer (removed 2026-07-27, see supergraph-stack.ts) -
    // provided.al2023 gets no automatic X-Ray instrumentation, but aws_xray
    // propagation alone still keeps the trace connected: confirmed directly
    // against a real deployed Lambda with no otlp exporter block at all that
    // subgraph segments still appear under the same trace ID as the
    // platform-native supergraph-graphql-test segment. Router's own internal
    // span (query_planning/compute_job timing) is the only thing lost by not
    // running an OTLP exporter - not connectivity - and cost ~170-400ms of
    // cold-start Init Duration for a span that covered ~11ms in a real trace.
    expect(routerYaml).toContain("aws_xray: true");
    expect(routerYaml).not.toMatch(/tracing:\s*\n\s*otlp:/);
  });

  it("enables introspection for the dashboard's GraphiQL/schema tooling", () => {
    expect(routerYaml).toContain("introspection: true");
  });

  it("nests telemetry.apollo batch_processor config under metrics/tracing, matching Router 2.x", () => {
    // Regression test: the flat telemetry.apollo.batch_processor shape this
    // used to assert was correct for Router 1.61.1, but Router 2.x rejects
    // it outright ("Additional properties are not allowed" the other way
    // around - a flat batch_processor no longer parses). Confirmed via the
    // real pinned v2.16.0 binary's own `router config upgrade`/
    // `config validate` against this exact file. Re-verify this shape
    // directly against apollo-router's apollo.rs source at the new tag
    // before ever bumping ROUTER_VERSION again.
    expect(routerYaml).toContain("metrics:");
    expect(routerYaml).toMatch(/metrics:\s*\n\s*usage_reports:\s*\n\s*batch_processor:/);
    expect(routerYaml).toMatch(/otlp:\s*\n\s*batch_processor:/);
    expect(routerYaml).toMatch(/tracing:\s*\n\s*batch_processor:/);
  });

  it("enables subgraph_metrics reporting to Apollo Studio", () => {
    // GraphOS Insights warned this graph had never reported subgraph-level
    // metrics, which requires Router >=2.7.0 plus this flag (GA as of
    // apollographql/router#8392). Ships over the metrics.otlp exporter, not
    // metrics.usage_reports (per `router config schema`'s description),
    // which is why metrics.otlp.batch_processor above also needs the
    // near-zero scheduled_delay, not just usage_reports.
    expect(routerYaml).toContain("subgraph_metrics: true");
  });

  it("gives Apollo Studio usage reporting a longer export timeout than the local OTLP one", () => {
    // Regression test: this exporter's real destination is a cross-region
    // HTTPS call to usage-reporting.api.apollographql.com, not localhost -
    // reusing OTLP's 3s local-latency timeout made every export attempt
    // fail with "operation timed out", confirmed live across multiple
    // warm, non-cold-start invocations.
    expect(routerYaml).toContain("max_export_timeout: 10s");
  });

  it("samples field-level instrumentation on every request, not the 1% default", () => {
    // Regression test: the default (TraceIdRatioBased(0.01)) could mean a
    // very long wait before any field-level data shows up in Studio's
    // Insights at all on this project's real traffic volume.
    expect(routerYaml).toContain("field_level_instrumentation_sampler: always_on");
  });
});
