import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, it, expect } from "vitest";
import { verifyChecksum } from "./build-router-package";

const routerYamlPath = join(dirname(fileURLToPath(import.meta.url)), "..", "router.yaml");
const routerYaml = readFileSync(routerYamlPath, "utf-8");

describe("verifyChecksum", () => {
  it("returns the hash when it matches the sha256sums.txt entry", () => {
    const artifactBuf = Buffer.from("fake router binary contents");
    const artifactName = "router-v1.61.1-x86_64-unknown-linux-gnu.tar.gz";
    const hash = createHash("sha256").update(artifactBuf).digest("hex");
    const sumsText = `${hash}  ${artifactName}\nsomeotherhash  some-other-file.tar.gz\n`;

    expect(verifyChecksum(artifactBuf, sumsText, artifactName)).toBe(hash);
  });

  it("throws on a hash mismatch instead of silently continuing", () => {
    const artifactBuf = Buffer.from("fake router binary contents");
    const artifactName = "router-v1.61.1-x86_64-unknown-linux-gnu.tar.gz";
    const sumsText = `0000000000000000000000000000000000000000000000000000000000000000  ${artifactName}\n`;

    expect(() => verifyChecksum(artifactBuf, sumsText, artifactName)).toThrow("sha256 mismatch");
  });

  it("throws when sha256sums.txt has no entry for the artifact", () => {
    const artifactBuf = Buffer.from("fake router binary contents");
    const artifactName = "router-v1.61.1-x86_64-unknown-linux-gnu.tar.gz";
    const sumsText = "somehash  some-unrelated-file.tar.gz\n";

    expect(() => verifyChecksum(artifactBuf, sumsText, artifactName)).toThrow(
      "no sha256sums.txt entry found"
    );
  });
});

// router.yaml is a static, checked-in file now (not generated by this
// script) - these tests read it directly, so they're regression tests
// against hand-edits rather than against a build step's own logic.
describe("router.yaml", () => {
  it("routes each subgraph name to API_BASE_URL via Router's own env templating", () => {
    expect(routerYaml).toContain("portfolio: ${env.API_BASE_URL}/portfolio");
    expect(routerYaml).toContain("pantry: ${env.API_BASE_URL}/pantry");
    expect(routerYaml).toContain("imposter: ${env.API_BASE_URL}/imposter");
    expect(routerYaml).toContain("design-studio: ${env.API_BASE_URL}/design-studio");
  });

  it("propagates the authorization header to subgraphs", () => {
    expect(routerYaml).toContain('named: "authorization"');
  });

  it("allows CORS from prod, test-env, local dev, and the embedded Sandbox UI on the actual response", () => {
    // Regression test: API Gateway's mock integration only answers the
    // OPTIONS preflight - it does not add CORS headers to the actual
    // GET/POST response, so without this config every browser (not curl)
    // silently discards every real response.
    expect(routerYaml).toContain("cors:");
    expect(routerYaml).toContain("https://www.petertran.au");
    expect(routerYaml).toContain("https://petertran.au");
    expect(routerYaml).toContain("https://test.petertran.au");
    expect(routerYaml).toContain("https://www.test.petertran.au");
    expect(routerYaml).toContain("http://localhost:5173");
    expect(routerYaml).toContain("http://localhost:3000");
    expect(routerYaml).toContain("https://studio.apollographql.com");
  });

  it("serves GraphQL at /graphql to match ApiGatewayStack's routing", () => {
    expect(routerYaml).toContain("path: /graphql");
  });

  it("enables sandbox and disables homepage together, never one without the other", () => {
    // Regression test: Router refuses to start at all if both are true
    // (homepage defaults to true) - crashed every cold start in production
    // once already ("sandbox and homepage cannot be enabled at the same
    // time"), only caught after real traffic was affected.
    expect(routerYaml).toMatch(/sandbox:\s*\n\s*enabled: true/);
    expect(routerYaml).toMatch(/homepage:\s*\n\s*enabled: false/);
  });

  it("exports traces via OTLP to the local ADOT collector with X-Ray propagation", () => {
    // provided.al2023 gets no automatic X-Ray instrumentation - this is
    // what actually gets traces to X-Ray at all (verified against a real
    // Lambda: zero traces without this, connected traces with it).
    expect(routerYaml).toContain("otlp:");
    expect(routerYaml).toContain("endpoint: http://localhost:4317");
    expect(routerYaml).toContain("aws_xray: true");
    expect(routerYaml).toContain("sampler: 1.0");
  });

  it("flushes OTLP trace spans almost immediately, not on the 5s default", () => {
    // Regression test: confirmed directly against a real Lambda that the
    // 5s default batch flush interval is longer than a fast invocation
    // survives before the execution environment freezes - spans never
    // left Router's buffer at all, so no trace ever reached X-Ray.
    expect(routerYaml).toContain("scheduled_delay: 1ms");
  });

  it("names the trace service instead of leaving it as OTel's unknown_service fallback", () => {
    // Without a service name, OTel defaults to "unknown_service:<binary
    // name>" - confirmed literally appearing as "unknown_service:router" in
    // ADOT collector logs before this. Sets both service_name and
    // resource["service.name"] since a real-Lambda spike couldn't
    // conclusively confirm which one the awsxrayexporter reads - X-Ray's
    // batch-get-traces never returned Router's own OTel-originated segment
    // to check directly. Cosmetic and confirmed low-risk either way.
    expect(routerYaml).toContain('service_name: "supergraph"');
    expect(routerYaml).toContain('service.name: "supergraph"');
  });

  it("enables introspection for the dashboard's GraphiQL/schema tooling", () => {
    expect(routerYaml).toContain("introspection: true");
  });

  it("keeps telemetry.apollo.batch_processor flat, not nested under a metrics key", () => {
    // Regression test: a later Router release nests this under
    // telemetry.apollo.metrics.usage_reports.batch_processor - using that
    // shape against the pinned ROUTER_VERSION crashed Router outright
    // ("Additional properties are not allowed ('metrics' was unexpected)"),
    // taking prod down for several minutes. Re-verify this shape directly
    // against apollo-router's apollo.rs source at the new tag before ever
    // bumping ROUTER_VERSION - don't just re-add the nested shape here.
    expect(routerYaml).not.toContain("usage_reports:");
    expect(routerYaml).toMatch(
      /apollo:\s*\n\s*field_level_instrumentation_sampler: always_on\s*\n\s*batch_processor:/
    );
  });

  it("gives Apollo Studio usage reporting a longer export timeout than the local OTLP one", () => {
    // Regression test: this exporter's real destination is a cross-region
    // HTTPS call to usage-reporting.api.apollographql.com, not localhost -
    // reusing OTLP's 3s local-latency timeout made every export attempt
    // fail with "operation timed out", confirmed live across multiple
    // warm, non-cold-start invocations.
    expect(routerYaml).toContain("max_export_timeout: 10s");
  });

  it("samples field-level instrumentation on every request, not the 1% default", () => {
    // Regression test: the default (TraceIdRatioBased(0.01)) could mean a
    // very long wait before any field-level data shows up in Studio's
    // Insights at all on this project's real traffic volume.
    expect(routerYaml).toContain("field_level_instrumentation_sampler: always_on");
  });
});
