import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { parse } from "graphql";
import { composeServices } from "@apollo/composition";
import { typeDefs as portfolioTypeDefs } from "../../portfolio/schema";
import { typeDefs as pantryTypeDefs } from "../../pantry/schema";
import { typeDefs as imposterTypeDefs } from "../../games/imposter/schema";

// Runs at build time (wired into turbo's "codegen" task, see turbo.json's
// "supergraph#codegen" override) instead of the gateway doing
// IntrospectAndCompose over live HTTPS on every cold start - that was costing
// 6-9s of cold-start Init Duration (3 subgraph SDL fetches, each of which
// could itself be a cold Lambda) and was the dominant reason the "provisioned"
// site still felt slow: PC only covers 1 concurrent execution, so any request
// that overlaps another (e.g. a single page load firing Hero + Footer's
// queries in parallel) spilled over to an on-demand cold start anyway.
//
// `url` below is a placeholder, never used for routing - handler.ts's
// buildService() reconstructs the real per-environment URL from `name` +
// API_BASE_URL at request time instead of trusting whatever's embedded in the
// composed schema, so this one composed artifact is correct for both prod and
// the on-demand test env without recomposing per environment.
const SERVICES = [
  {
    name: "portfolio",
    url: "https://composed-at-build-time.invalid/portfolio",
    typeDefs: parse(portfolioTypeDefs),
  },
  { name: "pantry", url: "https://composed-at-build-time.invalid/pantry", typeDefs: parse(pantryTypeDefs) },
  {
    name: "imposter",
    url: "https://composed-at-build-time.invalid/imposter",
    typeDefs: parse(imposterTypeDefs),
  },
];

const result = composeServices(SERVICES);

if (result.errors) {
  console.error("[compose-supergraph] composition failed:");
  for (const error of result.errors) console.error(` - ${error.message}`);
  process.exit(1);
}

const outFile = join(dirname(fileURLToPath(import.meta.url)), "..", "supergraph.generated.ts");

writeFileSync(
  outFile,
  "// AUTO-GENERATED by scripts/compose-supergraph.ts - do not edit by hand.\n" +
    `export const SUPERGRAPH_SDL = ${JSON.stringify(result.supergraphSdl)};\n`
);

console.log(`[compose-supergraph] wrote ${outFile}`);
